version: "3.3"
services:

  redis-sentinel:
    image: 127.0.0.1:5000/redis-sentinel
    volumes:
      - sentinel-conf:/etc/redis
    deploy:
      mode: global
    environment:
      - REDIS_MASTER_HOST=${REDIS_MASTER_IP}
      - SENTINEL_DOWN_AFTER=5000
      - SENTINEL_FAILOVER=15000
    networks:
      - rfbbot-net

  redis-master:
    image: 127.0.0.1:5000/master-redis
    volumes:
      - redis-data:/data
      - redis-conf:/etc/redis
    deploy:
      mode: global
      placement:
        constraints:
          - node.hostname == ${REDIS_MASTER_HOSTNAME}
    networks:
      - rfbbot-net

  redis-worker1-node1:
    image: 127.0.0.1:5000/master-redis
    volumes:
      - redis-data:/data
      - redis-conf:/etc/redis
    environment:
      - REDIS_MASTER_HOST=${REDIS_MASTER_IP}
    deploy:
      mode: global
      placement:
        constraints:
          - node.hostname == ${REDIS_WORKER_NODE1_HOSTNAME}
    networks:
      - rfbbot-net

  redis-worker2-node2:
    image: 127.0.0.1:5000/master-redis
    volumes:
      - redis-data:/data
      - redis-conf:/etc/redis
    environment:
      - REDIS_MASTER_HOST=${REDIS_MASTER_IP}
    deploy:
      mode: global
      placement:
        constraints:
          - node.hostname == ${REDIS_WORKER_NODE2_HOSTNAME}
    networks:
      - rfbbot-net

volumes:
  redis-data:
  redis-conf:
  sentinel-conf:
networks:
  rfbbot-net:
    external: true
