FROM python:3.8-slim-buster

WORKDIR /usr/src/app


RUN apt-get update \
    && apt-get -y install netcat gcc \
    && apt-get clean

COPY requirements.txt /usr/src/app
RUN pip install --no-cache-dir -r requirements.txt
COPY app.py /usr/src/app

EXPOSE 611

VOLUME ["/usr/src/app"]

ENTRYPOINT ["python", "app.py"]
